### ISSUE TITLE
Map rating buttons are broken

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#773]
Hovering over map rating stars in firefox turns them into a standard html select.

Scores do not seem to save if the select is used in any way.

**Comment by KingRaptor** [comment]
Happens on Chrome 45 too. Tooltip handling broken somehow?

**Comment by Skasi** [comment]
I remember it used to work a few weeks or months ago. I also remember I once saw a biiiiiiig empty tooltip when mousing over some very specific element, but sadly forgot which one. So maybe KR has a point, or maybe not.

**Comment by KingRaptor** [comment]
Mission ratings are also affected, it seems.

**Comment by Licho1** [comment]
fixed

**Comment by Anarchid** [comment]
Apparently this is now happening for a different reason.

**Comment by Licho1** [comment]
Fixed. 
Issue was caused by the presence of jquery.ui.stars.min.js

Site uses js bundler/minimizer which auto compiles and minimizes existing scripts into single file for faster dl. In the github we only had non min version and bundler generated correct min on the fly.
But on live server there was old min version of the script which bundler used instead -> causing non-functioning ratings..
Fixed by deleting min file.

**Comment by knorker** [comment]
the rating-star-buttons are not visually broken anymore but clicking them does nothing.
Nothing happens, no message, rating does not change...

**Comment by knorker** [comment]
the rating buttons/stars still do not function for me.

**Comment by Skasi** [comment]
Can confirm, still not working. Should prolly just be removed anyway though. Better track !votemap stats instead.
